name: dumdumcard
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.4
  http: ^1.1.0
  flip_card: ^0.7.0
  url_launcher: ^6.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/icon.png

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/backgrounds/bg.png
    - assets/images/backgrounds/pannel.png
    - assets/images/backgrounds/pannel2.png
    - assets/images/backgrounds/field.png
    - assets/images/backgrounds/backCard.png
    - assets/images/backgrounds/frontCard.png

    - assets/images/main_btn/join.png
    - assets/images/main_btn/play.png
    - assets/images/main_btn/scoreboard.png
    - assets/images/main_btn/scoreboard-disable.png
    - assets/images/main_btn/exit.png

    - assets/images/icon_btn/back.png
    - assets/images/icon_btn/close.png
    - assets/images/icon_btn/home.png
    - assets/images/icon_btn/pause.png
    - assets/images/icon_btn/reset.png
    - assets/images/icon_btn/star.png

    - assets/images/labels/title1.png
    - assets/images/labels/title2.png
    - assets/images/labels/username.png
    - assets/images/labels/time.png
    - assets/images/labels/score.png
    - assets/images/labels/complete.png
    - assets/images/labels/HS-scoreboard.png
    - assets/images/labels/HS-highscore.png
    - assets/images/labels/HS-name.png
    - assets/images/labels/HS-score.png
    - assets/images/labels/HS-time.png
    - assets/images/labels/HS-time.png

    - assets/images/symbols/1.png
    - assets/images/symbols/2.png
    - assets/images/symbols/3.png
    - assets/images/symbols/4.png
    - assets/images/symbols/5.png
    - assets/images/symbols/6.png
    - assets/images/symbols/7.png
    - assets/images/symbols/8.png
    - assets/images/symbols/9.png
    - assets/images/symbols/10.png
    - assets/images/symbols/11.png
    - assets/images/symbols/12.png
    - assets/images/symbols/13.png
    - assets/images/symbols/14.png
    - assets/images/symbols/15.png
    - assets/images/symbols/16.png
    - assets/images/symbols/17.png
    - assets/images/symbols/18.png
    - assets/images/symbols/19.png
    - assets/images/symbols/20.png
    - assets/images/symbols/21.png
    - assets/images/symbols/22.png
    - assets/images/symbols/23.png
    - assets/images/symbols/24.png
    - assets/images/symbols/25.png
    - assets/images/symbols/26.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
